In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.model_selection import train_test_split

torch.manual_seed(42)

In [3]:
CSV_FILENAME = "clean_autonomous_taxi_rides.csv"

In [4]:
df = pd.read_csv(CSV_FILENAME)
df.head(5)

   trip_distance_miles  pickup_hour  passenger_count  ride_duration_min
0                  2.5            8                1                9.0
1                  4.0            9                1               12.0
2                  6.0           17                2               18.0
3                  8.5           18                2               24.0
4                 10.0            7                1               27.0

In [7]:
duration_col = "ride_duration_min"
MAX_ACCEPTABLE_DURATION_MIN = 25.0
df["accept_request"] = (df[duration_col] <= MAX_ACCEPTABLE_DURATION_MIN).astype("float32")
df

,trip_distance_miles,pickup_hour,passenger_count,ride_duration_min,accept_request
0,2.5,8,1,9.0,1.0
1,4.0,9,1,12.0,1.0
2,6.0,17,2,18.0,1.0
3,8.5,18,2,24.0,1.0
4,10.0,7,1,27.0,0.0
5,12.0,12,3,31.0,0.0
6,15.0,16,2,39.0,0.0
7,18.0,20,1,46.0,0.0

In [8]:
df["accept_request"].value_counts().sort_index()

accept_request
0.0    4
1.0    4
Name: count, dtype: int64

In [9]:
feature_col = "trip_distance_miles"
target_col = "accept_request"
df[[feature_col, target_col]]

   trip_distance_miles  accept_request
0                  2.5             1.0
1                  4.0             1.0
2                  6.0             1.0
3                  8.5             1.0
4                 10.0             0.0
5                 12.0             0.0
6                 15.0             0.0
7                 18.0             0.0

In [10]:
x = df[[feature_col]].values.astype("float32")
y = df[[target_col]].values.astype("float32")

In [11]:
print("x shape:", x.shape)
print("y shape:", y.shape)

x shape: (8, 1)
y shape: (8, 1)